### ISSUE TITLE
netdata agent update to min v.1.34.1 

### ISSUE THREAD

**Issue by ciechompl** [Gamma-Software/netdata-homeassistant-addon#7]
Netdata console "screaming" for agent update :) 
Currently v.1.33.1 is used by this add-on but netdata says that minimum v.1.34.1 should be used due to security bug.

**Comment by ahmedelakkad** [comment]
Yes! Kindly update guys!

**Comment by Gamma-Software** [comment]
Hey !
The issue is that I can’t find the way to create persistant docker volumes in HomeAssistant Addons.
This is needed as it’s recommended by the Netdata team 
https://community.netdata.cloud/t/containerized-netdata-agent-update-and-node-claiming/86/5
I’ll ask for help in the HA community to find a solution to create volumes

**Comment by Gamma-Software** [comment]
Hey !
I’ll update it today

**Comment by ahmedelakkad** [comment]
Thanks a million!

**Comment by Gamma-Software** [comment]
The version 2.1.1 of the addon will install the latest Netdata version up to date (v1.36.1)
